routes/admin.php
<?php


use App\Http\Controllers\HomeController;
use App\Http\Controllers\OrderController;

use Illuminate\Support\Facades\Artisan;

use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\AddressController;


use App\Http\Controllers\EngineerController;
use App\Http\Controllers\MinhazController;
use App\Http\Controllers\PhotoController;
use App\Http\Controllers\ServiceProviderController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\WarrantyController;
use App\Http\Controllers\RentalController;
use App\Http\Controllers\SiteVisitController;
use App\Http\Controllers\CouponController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\ServiceListController;
use App\Http\Controllers\BrandController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//








Route::get('/altest', [HomeController::class, 'altest'])->name('altest')->middleware(['auth']);

Route::group(['middleware' => ['is-admin']], function () {



    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('products', ProductController::class);
    Route::resource('engineers', EngineerController::class);
    Route::resource('photos', PhotoController::class);
    Route::get('photos/{photo}', [PhotoController::class, 'delete'])->name('deletePhoto');
    Route::resource('customer', CustomerController::class);
    Route::resource('addresses', AddressController::class);
    Route::resource('coupon', CouponController::class);
    Route::resource('categories', CategoryController::class);
    Route::resource('services', ServiceListController::class);
    Route::resource('brands', BrandController::class);
    Route::get('services/{service}', [ServiceListController::class, 'delete'])->name('delete_service_list');
    Route::get('brands/{brand}', [BrandController::class, 'delete'])->name('delete_brand_list');

    Route::get('orders/pending-list', [OrderController::class, 'pendingList'])->name('pending_order_list');
    Route::get('orders/assigned-list', [OrderController::class, 'assignedList'])->name('assigned_order_list');

    Route::get('orders/assign-provider/{id?}', [OrderController::class, 'assignServiceProvider'])->name('assign.provider');
    Route::post('orders/set-assign-provider', [OrderController::class, 'setAssignServiceProvider'])->name('set.assign.provider');
    Route::get('orders/details', [OrderController::class, 'orderDetails'])->name('order_details');
    Route::get('/cancel/order/{id?}', [OrderController::class, 'cancelOrder'])->name('cancel.order');


    Route::get('users', [UserController::class, 'index'])->name('users.index');

    Route::get('photos/{photo}', [PhotoController::class, 'delete'])->name('deletePhoto');

    Route::any('service-providers/list', [ServiceProviderController::class, 'index'])->name('service_provider_list_admin');
    Route::get('service-providers/create', [ServiceProviderController::class, 'create'])->name('service_provider_create_admin');
    Route::post('service-providers/store', [ServiceProviderController::class, 'store'])->name('service_provider_store_admin');
    Route::get('service-providers/profile/{id}', [ServiceProviderController::class, 'show'])->name('service_provider_profile');
    Route::get('/service-providers/details/{id}', [ServiceProviderController::class, 'details'])->name('service_provider_details');
    Route::get('service-providers/{id}', [ServiceProviderController::class, 'destroy'])->name('deleteProvider');

    //warranty info get start
    Route::get('/warranty_show', [WarrantyController::class, 'show'])->name('warranty.show');
    Route::get('/warranty_delete/{id}', [WarrantyController::class, 'delete'])->name('warranty.delete');
    //warranty info get end

    //rental info get start
    Route::get('/rental_show', [RentalController::class, 'show'])->name('rental.show');
    Route::get('/rental_delete/{id}', [RentalController::class, 'delete'])->name('rental.delete');
    //rental info get end

    //site visit info get start
    Route::get('/site_visit_show', [SiteVisitController::class, 'show'])->name('site.visit.show');
    Route::get('/site_visit_delete/{id}', [SiteVisitController::class, 'delete'])->name('site.visit.delete');
    //site visit info get end

    Route::any('/addresses/{address}/delete', [AddressController::class, 'destroy'])->name('addresses_destroy');
    Route::get('/addresses/set_default/{id}', [AddressController::class, 'set_default'])->name('addresses.set_default');

    //Coupons
    Route::post('/coupon/get_form', [CouponController::class, 'get_coupon_form'])->name('coupon.get_coupon_form');
    Route::post('/coupon/{id}/get_form_edit', [CouponController::class, 'get_coupon_form_edit'])->name('get_coupon_form_edit');
    Route::get('/coupon/{coupon}/delete', [CouponController::class, 'destroy'])->name('coupon_destroy');
    //search
    Route::get('/search', [SearchController::class, 'search'])->name('search');
    Route::get('/search?q={search}', [SearchController::class, 'search'])->name('suggestion.search');

    //Cart or Checkout route start
    Route::match(['GET', 'POST'], '/checkout', [HomeController::class, 'checkout'])->name('checkout');
    Route::get('/search', [SearchController::class, 'search'])->name('search');
    Route::get('/search?q={search}', [SearchController::class, 'search'])->name('suggestion.search');

    Route::get('/sub-categories', 'CategoryController@subCategory')->name('subCategory');
    //for popular category status change

});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Artisan;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\AddressController;
use App\Http\Controllers\EngineerController;
use App\Http\Controllers\MinhazController;
use App\Http\Controllers\PhotoController;
use App\Http\Controllers\ServiceProviderController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\WarrantyController;
use App\Http\Controllers\RentalController;
use App\Http\Controllers\SiteVisitController;
use App\Http\Controllers\CouponController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ServiceListController;
use App\Http\Controllers\ServiceController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//

Auth::routes();

Route::get(
    '/clear',
    function () {
        Artisan::call('cache:clear');
        Artisan::call('config:clear');
        Artisan::call('route:clear');
        Artisan::call('view:clear');

        Toastr::success('Config Cache Cleared Successfully', 'Success', ["closeButton" => true, "debug" => false, "newestOnTop" => false, "progressBar" => true, "positionClass" => "toast-bottom-left", "preventDuplicates" => false, "onclick" => null, "showDuration" => "300", "hideDuration" => "1000", "timeOut" => "5000", "extendedTimeOut" => "1000", "showEasing" => "swing", "hideEasing" => "linear", "showMethod" => "fadeIn", "hideMethod" => "fadeOut"]);

    return redirect()->back();
    }
);

Route::get(
    '/setup',
    function () {
        Artisan::call('migrate');
    }
);

Route::get('/min', function () {
    Toastr::success('Categories our customers love to check out', 'Success', ["closeButton" => true, "debug" => false, "newestOnTop" => false, "progressBar" => true, "positionClass" => "toast-bottom-left", "preventDuplicates" => false, "onclick" => null, "showDuration" => "300", "hideDuration" => "1000", "timeOut" => "5000", "extendedTimeOut" => "1000", "showEasing" => "swing", "hideEasing" => "linear", "showMethod" => "fadeIn", "hideMethod" => "fadeOut"]);

    return redirect()->back();
});

Route::get('/home', [HomeController::class, 'index'])->name('home')->middleware('is-admin');
Route::group(['middleware' => ['auth']], function () {

    //for popular category status change
    Route::get('/popular-category-status/{id}', [CategoryController::class, 'popularStatus'])->name('popular.category.status');


    Route::get('/home/view', [HomeController::class, 'homeView2'])->name('home_view');
});

Route::get('/', [HomeController::class, 'homeView'])->name('homeView');
Route::match(['GET', 'POST'], '/customer_login', [UserController::class, 'customer_login'])->name('customer_login');
Route::post('/customer_register', [UserController::class, 'customer_register'])->name('customer_register');
Route::get('/logout', [UserController::class, 'customer_logout'])->name('logout');
Route::match(['GET', 'POST'], '/customer_login', [UserController::class, 'customer_login'])->name('customer_login');

Route::get('/logout', [UserController::class, 'customer_logout'])->name('logout');

Route::get('/users/login', [HomeController::class, 'customer_login'])->name('customer.login');
Route::get('/users/registration', [HomeController::class, 'customer_registration'])->name('customer.registration');
Route::get('/service-provider-registration', [HomeController::class, 'service_provider_registration'])->name('service_provider.registration');

// all auth url
Route::group(['middleware' => ['auth']], function () {


});

Route::group(['middleware' => ['is-user']], function () {
    Route::get('/dashboard', [HomeController::class, 'user_dashboard'])->name('user.dashboard');
    Route::post('service-provider-registration', [UserController::class, 'service_provider_register'])->name('service_provider_register');

});

//provider


Route::group(['prefix' =>'provider', 'middleware' => ['is-user']], function(){
    Route::get('/service_add', [ServiceController::class, 'create'])->name('service_provider.add_service');
    Route::post('/service_add', [ServiceController::class, 'store'])->name('service_provider_service_store');
});



Route::get('/service-details/{slug}', [ServiceController::class, 'serviceDetails'])->name('service_details');

Route::get('/profile', [ServiceProviderController::class, 'serviceProviderProfileCreate'])->name('service_provider_create');
Route::post('upazilas_name', [ServiceProviderController::class, 'upazilas_name'])->name('upazilas_name');
Route::post('service-providers', [ServiceProviderController::class, 'serviceProviderStore'])->name('service_provider_profile_store');

 Route::get('/my_service', [HomeController::class, 'provider_services_list'])->name('service_provider.services');

    Route::get('/orders', [HomeController::class, 'service_provider_orders'])->name('service_provider.orders');

// check coupons
Route::post('/coupon-check', [HomeController::class, 'couponCheck'])->name('coupon.check');

//Warranty route
Route::match(['GET', 'POST'], '/warranty', [WarrantyController::class, 'index'])->name('warranty');

//Rental route start
Route::match(['GET', 'POST'], '/rental', [RentalController::class, 'index'])->name('rental');

//Site Visit route start
Route::match(['GET', 'POST'], '/site_visit', [SiteVisitController::class, 'index'])->name('site.visit');


//Cart or Checkout route start
Route::match(['GET', 'POST'], '/checkout', [HomeController::class, 'checkout'])->name('checkout');
Route::get('/search', [SearchController::class, 'search'])->name('search');
Route::get('/search?q={search}', [SearchController::class, 'search'])->name('suggestion.search');



/*desgin end*/
/*desgin start*/

Route::get('/service_list', function () {
    return view('frontend.customer.service_list');
});
Route::get('checkout-summery', [ServiceProviderController::class, 'checkout'])->name('checkout_summery');
Route::get('/cart', function () {
    return view('frontend.cart');
})->name('view_cart');
/* sobuj desgin end*/

resources/views/backend/image_file/create.blade.php
@extends('backend.layouts.app')

@section('title', 'Uploaded Image')


@section('js')


@endsection
@section('css')
<style>

</style>
@endsection


@section('content')

<!-- BEGIN CONTENT BODY -->
<div class="page-content">
    <!-- BEGIN PAGE HEADER-->


    @include('backend.include.beginPageHeader')


    <!-- END PAGE HEADER-->

    <div class="row">
            <div class="col-md-12" style="margin-top:20px">
                <div class="portlet box blue">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-gift"></i>Image Upload Form
                        </div>
                        <div class="actions">
                            <div class="btn-set pull-right">
                            <a href="{{route('photos.index')}}"><button type="button" class="btn red">List</button></a>
                            </div>
                        </div>

                    </div>
                    <div class="portlet-body form">


                        <!-- BEGIN FORM-->
                        <form action="{{route('photos.index')}}" method="post" class="form-horizontal"
                              enctype="multipart/form-data">
                            @csrf
                            <div class="form-body">



                            <div class="form-group">
                                        <label class="col-md-3 control-label">Image Title :</label>
                                        <div class="col-md-4">
                                            <input name="image_title" type="text" class="form-control" value="{{ old('image_title') }}"
                                                placeholder="write image title">
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 control-label">Meta Keywords :</label>
                                        <div class="col-md-4">
                                            <input name="image_meta_keywords" type="text" value="{{ old('image_meta_keywords') }}" class="form-control"
                                                placeholder="write image meta keywords">
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 control-label">Image Type :</label>
                                        <div class="col-md-4">
                                            <select id="single" name="image_type" class="form-control">
                                                <option value="">Select Type</option>
                                                <option value="1" class="active">Type 1</option>
                                                <option value="2">Type 2</option>

                                            </select>
                                        </div>
                                    </div>


                                    <div class="form-group">
                                        <label class="col-md-3 control-label">Image File :</label>
                                        <div class="col-md-4">
                                            <input name="image_file" type="file" class="form-control"
                                                placeholder="Image File Select">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-3 control-label">Description :</label>
                                        <div class="col-md-6">
                                        <textarea name="image_meta_description" id="image_meta_description"  class="form-control"
                                                placeholder="Description"></textarea>
                                        </div>
                                    </div> 

                            </div>

                            <div class="form-actions top">
                                <div class="row">
                                    <div class="col-md-offset-4 col-md-8">
                                        <button type="submit" class="btn green">Submit</button>
                                        <button type="button" class="btn default">Cancel</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <!-- END FORM-->
                    </div>
                </div>
            </div>
        </div>


</div>
    <!-- END CONTENT BODY -->
@endsection

resources/views/backend/image_file/index.blade.php
@extends('backend.layouts.app')

@section('title', 'Uploaded Image List')


@section('js')


@endsection
@section('css')
<style>

</style>
@endsection


@section('content')

<!-- BEGIN CONTENT BODY -->
<div class="page-content">
    <!-- BEGIN PAGE HEADER-->


    @include('backend.include.beginPageHeader')


    <!-- END PAGE HEADER-->

    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet box green">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-user"></i> Uploaded Image List </div>
                    <div style="color:black" class="tools"> <a style="color:black;" href="{{route('photos.create')}}"><i class="fa fa-plus" style="color:black "></i> Add New Image/Banner
                        </a></div>
                </div>
                <div class="portlet-body">
                    <table class="table table-striped table-bordered table-hover dt-responsive" width="100%" id="sample_3" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th class="all">#</th>
                                <th class="min-phone-l" style="text-align: center;">Image</th>
                                <th class="min-phone-l">Image Title</th>
                                <th class="min-tablet">Image Type</th>
                                <th class="desktop">Image Status</th>

                                <th class="all">***</th>
                            </tr>
                        </thead>
                        <tbody>

                          @foreach($photo_info as $ph_info)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td style="text-align: center;"><img style="height:100px;width:100px;" src="{{$ph_info->image_path}}"></td>
                                    <td>{{$ph_info->image_title}}</td>
                                    <td>{{$ph_info->image_type}}</td>
                                    <td><?php if($ph_info->image_type ==1){echo "Active";}else{echo "Inactive";} ?></td>


                                    <td>
                                        <div class="btn-group">
                                            <button class="btn btn-xs green dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false"> Action
                                                <i class="fa fa-angle-down"></i>
                                            </button>
                                            <ul class="dropdown-menu pull-left" role="menu">
                                                <li>
                                                    <a style="border: none;" href="{{route('photos.edit', $ph_info->id)}}">
                                                        <span class="item">
                                                            <span aria-hidden="true" class="icon-note icons"></span> Edit</a>
                                                </li>

                                                <li>
                                                    <a style="border: none;" href="{{route('deletePhoto', $ph_info->id)}}"><i class="fa fa-trash"></i> Remove</a>
                                                </li>

                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach

                        </tbody>
                    </table>
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>

    </div>

</div>

<!-- END CONTENT BODY -->
@endsection