routes/admin.php
<?php


use App\Http\Controllers\HomeController;
use App\Http\Controllers\OrderController;

use Illuminate\Support\Facades\Artisan;

use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\AddressController;


use App\Http\Controllers\EngineerController;
use App\Http\Controllers\MinhazController;
use App\Http\Controllers\PhotoController;
use App\Http\Controllers\ServiceProviderController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\WarrantyController;
use App\Http\Controllers\RentalController;
use App\Http\Controllers\SiteVisitController;
use App\Http\Controllers\CouponController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\ServiceListController;
use App\Http\Controllers\BrandController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//








Route::get('/altest', [HomeController::class, 'altest'])->name('altest')->middleware(['auth']);

Route::group(['middleware' => ['is-admin']], function () {



    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('products', ProductController::class);
    Route::resource('engineers', EngineerController::class);
    Route::resource('photos', PhotoController::class);
    Route::get('photos/{photo}', [PhotoController::class, 'delete'])->name('deletePhoto');
    Route::resource('customer', CustomerController::class);
    Route::resource('addresses', AddressController::class);
    Route::resource('coupon', CouponController::class);
    Route::resource('categories', CategoryController::class);
    Route::resource('services', ServiceListController::class);
    Route::resource('brands', BrandController::class);
    Route::get('services/{service}', [ServiceListController::class, 'delete'])->name('delete_service_list');
    Route::get('brands/{brand}', [BrandController::class, 'delete'])->name('delete_brand_list');

    Route::get('orders/pending-list', [OrderController::class, 'pendingList'])->name('pending_order_list');
    Route::get('orders/assigned-list', [OrderController::class, 'assignedList'])->name('assigned_order_list');

    Route::get('orders/assign-provider/{id?}', [OrderController::class, 'assignServiceProvider'])->name('assign.provider');
    Route::post('orders/set-assign-provider', [OrderController::class, 'setAssignServiceProvider'])->name('set.assign.provider');
    Route::get('orders/details', [OrderController::class, 'orderDetails'])->name('order_details');
    Route::get('/cancel/order/{id?}', [OrderController::class, 'cancelOrder'])->name('cancel.order');


    Route::get('users', [UserController::class, 'index'])->name('users.index');

    Route::get('photos/{photo}', [PhotoController::class, 'delete'])->name('deletePhoto');

    Route::any('service-providers/list', [ServiceProviderController::class, 'index'])->name('service_provider_list_admin');
    Route::get('service-providers/create', [ServiceProviderController::class, 'create'])->name('service_provider_create_admin');
    Route::post('service-providers/store', [ServiceProviderController::class, 'store'])->name('service_provider_store_admin');
    Route::get('service-providers/profile/{id}', [ServiceProviderController::class, 'show'])->name('service_provider_profile');
    Route::get('/service-providers/details/{id}', [ServiceProviderController::class, 'details'])->name('service_provider_details');
    Route::get('service-providers/{id}', [ServiceProviderController::class, 'destroy'])->name('deleteProvider');

    //warranty info get start
    Route::get('/warranty_show', [WarrantyController::class, 'show'])->name('warranty.show');
    Route::get('/warranty_delete/{id}', [WarrantyController::class, 'delete'])->name('warranty.delete');
    //warranty info get end

    //rental info get start
    Route::get('/rental_show', [RentalController::class, 'show'])->name('rental.show');
    Route::get('/rental_delete/{id}', [RentalController::class, 'delete'])->name('rental.delete');
    //rental info get end

    //site visit info get start
    Route::get('/site_visit_show', [SiteVisitController::class, 'show'])->name('site.visit.show');
    Route::get('/site_visit_delete/{id}', [SiteVisitController::class, 'delete'])->name('site.visit.delete');
    //site visit info get end

    Route::any('/addresses/{address}/delete', [AddressController::class, 'destroy'])->name('addresses_destroy');
    Route::get('/addresses/set_default/{id}', [AddressController::class, 'set_default'])->name('addresses.set_default');

    //Coupons
    Route::post('/coupon/get_form', [CouponController::class, 'get_coupon_form'])->name('coupon.get_coupon_form');
    Route::post('/coupon/{id}/get_form_edit', [CouponController::class, 'get_coupon_form_edit'])->name('get_coupon_form_edit');
    Route::get('/coupon/{coupon}/delete', [CouponController::class, 'destroy'])->name('coupon_destroy');
    //search
    Route::get('/search', [SearchController::class, 'search'])->name('search');
    Route::get('/search?q={search}', [SearchController::class, 'search'])->name('suggestion.search');

    //Cart or Checkout route start
    Route::match(['GET', 'POST'], '/checkout', [HomeController::class, 'checkout'])->name('checkout');
    Route::get('/search', [SearchController::class, 'search'])->name('search');
    Route::get('/search?q={search}', [SearchController::class, 'search'])->name('suggestion.search');

    Route::get('/sub-categories', 'CategoryController@subCategory')->name('subCategory');
    //for popular category status change

});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Artisan;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\AddressController;
use App\Http\Controllers\EngineerController;
use App\Http\Controllers\MinhazController;
use App\Http\Controllers\PhotoController;
use App\Http\Controllers\ServiceProviderController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\WarrantyController;
use App\Http\Controllers\RentalController;
use App\Http\Controllers\SiteVisitController;
use App\Http\Controllers\CouponController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ServiceListController;
use App\Http\Controllers\ServiceController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//

Auth::routes();

Route::get(
    '/clear',
    function () {
        Artisan::call('cache:clear');
        Artisan::call('config:clear');
        Artisan::call('route:clear');
        Artisan::call('view:clear');

        Toastr::success('Config Cache Cleared Successfully', 'Success', ["closeButton" => true, "debug" => false, "newestOnTop" => false, "progressBar" => true, "positionClass" => "toast-bottom-left", "preventDuplicates" => false, "onclick" => null, "showDuration" => "300", "hideDuration" => "1000", "timeOut" => "5000", "extendedTimeOut" => "1000", "showEasing" => "swing", "hideEasing" => "linear", "showMethod" => "fadeIn", "hideMethod" => "fadeOut"]);

    return redirect()->back();
    }
);

Route::get(
    '/setup',
    function () {
        Artisan::call('migrate');
    }
);

Route::get('/min', function () {
    Toastr::success('Categories our customers love to check out', 'Success', ["closeButton" => true, "debug" => false, "newestOnTop" => false, "progressBar" => true, "positionClass" => "toast-bottom-left", "preventDuplicates" => false, "onclick" => null, "showDuration" => "300", "hideDuration" => "1000", "timeOut" => "5000", "extendedTimeOut" => "1000", "showEasing" => "swing", "hideEasing" => "linear", "showMethod" => "fadeIn", "hideMethod" => "fadeOut"]);

    return redirect()->back();
});

Route::get('/home', [HomeController::class, 'index'])->name('home')->middleware('is-admin');
Route::group(['middleware' => ['auth']], function () {

    //for popular category status change
    Route::get('/popular-category-status/{id}', [CategoryController::class, 'popularStatus'])->name('popular.category.status');


    Route::get('/home/view', [HomeController::class, 'homeView2'])->name('home_view');
});

Route::get('/', [HomeController::class, 'homeView'])->name('homeView');
Route::match(['GET', 'POST'], '/customer_login', [UserController::class, 'customer_login'])->name('customer_login');
Route::post('/customer_register', [UserController::class, 'customer_register'])->name('customer_register');
Route::get('/logout', [UserController::class, 'customer_logout'])->name('logout');
Route::match(['GET', 'POST'], '/customer_login', [UserController::class, 'customer_login'])->name('customer_login');

Route::get('/logout', [UserController::class, 'customer_logout'])->name('logout');

Route::get('/users/login', [HomeController::class, 'customer_login'])->name('customer.login');
Route::get('/users/registration', [HomeController::class, 'customer_registration'])->name('customer.registration');
Route::get('/service-provider-registration', [HomeController::class, 'service_provider_registration'])->name('service_provider.registration');

// all auth url
Route::group(['middleware' => ['auth']], function () {


});

Route::group(['middleware' => ['is-user']], function () {
    Route::get('/dashboard', [HomeController::class, 'user_dashboard'])->name('user.dashboard');
    Route::post('service-provider-registration', [UserController::class, 'service_provider_register'])->name('service_provider_register');

});

//provider


Route::group(['prefix' =>'provider', 'middleware' => ['is-user']], function(){
    Route::get('/service_add', [ServiceController::class, 'create'])->name('service_provider.add_service');
    Route::post('/service_add', [ServiceController::class, 'store'])->name('service_provider_service_store');
});



Route::get('/service-details/{slug}', [ServiceController::class, 'serviceDetails'])->name('service_details');

Route::get('/profile', [ServiceProviderController::class, 'serviceProviderProfileCreate'])->name('service_provider_create');
Route::post('upazilas_name', [ServiceProviderController::class, 'upazilas_name'])->name('upazilas_name');
Route::post('service-providers', [ServiceProviderController::class, 'serviceProviderStore'])->name('service_provider_profile_store');

 Route::get('/my_service', [HomeController::class, 'provider_services_list'])->name('service_provider.services');

    Route::get('/orders', [HomeController::class, 'service_provider_orders'])->name('service_provider.orders');

// check coupons
Route::post('/coupon-check', [HomeController::class, 'couponCheck'])->name('coupon.check');

//Warranty route
Route::match(['GET', 'POST'], '/warranty', [WarrantyController::class, 'index'])->name('warranty');

//Rental route start
Route::match(['GET', 'POST'], '/rental', [RentalController::class, 'index'])->name('rental');

//Site Visit route start
Route::match(['GET', 'POST'], '/site_visit', [SiteVisitController::class, 'index'])->name('site.visit');


//Cart or Checkout route start
Route::match(['GET', 'POST'], '/checkout', [HomeController::class, 'checkout'])->name('checkout');
Route::get('/search', [SearchController::class, 'search'])->name('search');
Route::get('/search?q={search}', [SearchController::class, 'search'])->name('suggestion.search');



/*desgin end*/
/*desgin start*/

Route::get('/service_list', function () {
    return view('frontend.customer.service_list');
});
Route::get('checkout-summery', [ServiceProviderController::class, 'checkout'])->name('checkout_summery');
Route::get('/cart', function () {
    return view('frontend.cart');
})->name('view_cart');
/* sobuj desgin end*/

app/Models/Coupon.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

class Coupon extends Model
{
    use HasFactory;
    protected $guarded = [];
    protected $value = ['created_at', 'updated_at'];

    public function getCreatedAtAttribute($value)
    {
        $date = Carbon::parse($value);
        return $date->format('d-m-Y');
    }
}

resources/views/backend/coupons/cart_base_coupon.blade.php
<div class="card-header mb-2">
    <h3 class="h6"> Add Your Cart Base Coupon </h3>
</div>
<div class="form-group row">
    <label class="col-lg-3 col-from-label" for="coupon_code"> Coupon code </label>
    <div class="col-lg-5">
        <input type="text" placeholder=" Coupon code " id="coupon_code" name="coupon_code" class="form-control" required>
    </div>
</div>
<div class="form-group row">
   <label class="col-lg-3 col-from-label"> Minimum Shopping </label>
   <div class="col-lg-5">
      <input type="number" lang="en" min="0" step="0.01" placeholder=" Minimum Shopping " name="min_buy" class="form-control" required>
   </div>
</div>
<div class="form-group row">
   <label class="col-lg-3 col-from-label"> Discount </label>
   <div class="col-lg-3">
      <input type="number" lang="en" min="0" step="0.01" placeholder=" Discount " name="discount" class="form-control" required>
   </div>
   <div class="col-lg-2">
       <select class="form-control aiz-selectpicker" name="discount_type">
           <option value="amount"> Amount </option>
           <option value="percent"> Percent </option>
       </select>
   </div>
</div>
<div class="form-group row">
   <label class="col-lg-3 col-from-label"> Maximum Discount Amount </label>
   <div class="col-lg-5">
      <input type="number" lang="en" min="0" step="0.01" placeholder=" Maximum Discount Amount " name="max_discount" class="form-control" required>
   </div>
</div>
<div class="form-group row">
    <label class="col-sm-3 control-label" for="start_date" style="text-align: left;"> Date </label>
    <div class="col-sm-5">
      <input type="text" class="form-control aiz-date-range" name="date_range" placeholder="Select Date">
    </div>
</div>

<script type="text/javascript">

    $(document).ready(function(){
        $('.aiz-date-range').daterangepicker();
    });
</script>

resources/views/backend/coupons/cart_base_coupon_edit.blade.php
@php
    $coupon_det = json_decode($coupon->details);
@endphp

<div class="card-header mb-2">
   <h3 class="h6"> Edit Your Cart Base Coupon </h3>
</div>
<div class="form-group row">
   <label class="col-lg-3 col-from-label" for="coupon_code"> Coupon code </label>
   <div class="col-lg-9">
       <input type="text" value="{{$coupon->code}}" id="coupon_code" name="coupon_code" class="form-control" required>
   </div>
</div>


<div class="form-group row">
  <label class="col-lg-3 col-from-label"> Minimum Shopping </label>
  <div class="col-lg-9">
     <input type="number" lang="en" min="0" step="0.01" name="min_buy" class="form-control" value="{{ $coupon_det->min_buy }}" required>
  </div>
</div>
<div class="form-group row">
   <label class="col-lg-3 col-from-label"> Discount </label>
   <div class="col-lg-7">
       <input type="number" lang="en" min="0" step="0.01" placeholder=" Discount " name="discount" class="form-control" value="{{ $coupon->discount }}" required>
   </div>
   <div class="col-lg-2">
       <select class="form-control aiz-selectpicker" name="discount_type">
           <option value="amount" @if ($coupon->discount_type == 'amount') selected  @endif > Amount </option>
           <option value="percent" @if ($coupon->discount_type == 'percent') selected  @endif> Percent </option>
       </select>
   </div>
</div>
<div class="form-group row">
  <label class="col-lg-3 col-from-label"> Maximum Discount Amount </label>
  <div class="col-lg-9">
     <input type="number" lang="en" min="0" step="0.01" placeholder=" Maximum Discount Amount " name="max_discount" class="form-control" value="{{ $coupon_det->max_discount }}" required>
  </div>
</div>

@php
  $start_date = date('m/d/Y', $coupon->start_date);
  $end_date = date('m/d/Y', $coupon->end_date);
@endphp
<div class="form-group row">
    <label class="col-sm-3 control-label" for="start_date"> Date </label>
    <div class="col-sm-9">
      <input type="text" class="form-control aiz-date-range" value="{{ $start_date .' - '. $end_date }}" name="date_range" placeholder="Select Date">
    </div>
</div>


<script type="text/javascript">
   $(document).ready(function(){
       $('.aiz-selectpicker').selectpicker();
       $('.aiz-date-range').daterangepicker();
   });

</script>

resources/views/backend/coupons/create.blade.php
@extends('backend.layouts.app')

@section('title', 'Coupon List')


@section('js')
<script type="text/javascript">

    function coupon_form(){
        var coupon_type = $('#coupon_type').val();
        
		$.post('{{ route('coupon.get_coupon_form') }}',{_token:'{{ csrf_token() }}', coupon_type:coupon_type}, function(data){
            $('#coupon_form').html(data);

         //    $('#demo-dp-range .input-daterange').datepicker({
         //        startDate: '-0d',
         //        todayBtn: "linked",
         //        autoclose: true,
         //        todayHighlight: true
        	// });
		});
    }

</script>

@endsection
@section('css')
<style>

</style>
@endsection

@section('content')
<div class="page-content">
@include('backend.include.beginPageHeader')
<div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet box green">

                <div class="portlet-title">

                <div class="caption">
                            <i class="fa fa-globe"></i> Coupon Details</div>
                        <div class="tools"> </div>

                </div>
                <div class="portlet-body">
              <form class="form-horizontal" action="{{ route('coupon.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="form-group row">
                    <label class="col-lg-3 col-from-label" for="name">Coupon Type</label>
                    <div class="col-lg-5">
                        <select name="coupon_type" id="coupon_type" class="form-control aiz-selectpicker" onchange="coupon_form()" required>
                            <option value="">Select One</option>
                            <option value="category_base">For Category</option>
                            <option value="cart_base">For Total Orders</option>
                        </select>
                    </div>
                </div>

                <div id="coupon_form">

                </div>
                <div class="form-group mb-0 text-right">
                    <button type="submit" class="btn btn-primary" style="margin-right: 15px;">Save</button>
                </div>
              </from>
              </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>

    </div>
</div>
@endsection

resources/views/backend/coupons/edit.blade.php
@extends('backend.layouts.app')

@section('title', 'Coupon Edit')


@section('js')
<script type="text/javascript">

    function coupon_form(){
        var coupon_type = $('#coupon_type').val();
        
		$.post('{{ route('coupon.get_coupon_form') }}',{_token:'{{ csrf_token() }}', coupon_type:coupon_type}, function(data){
            $('#coupon_form').html(data);

		});
    }

</script>

@endsection
@section('css')
<style>

</style>
@endsection

@section('content')

<div class="page-content">
@include('backend.include.beginPageHeader')
<div class="row">
        <div class="col-md-10">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet box green">

                <div class="portlet-title">

                <div class="caption">
                            <i class="fa fa-globe"></i> Coupon Details</div>
                        <div class="tools"> </div>

                </div>
                <div class="portlet-body">
            <form action="{{ route('coupon.update', $coupon->id) }}" method="POST">
                <input name="_method" type="hidden" value="PATCH">
            	@csrf
                <div class="card-body">
                    <input type="hidden" name="id" value="{{ $coupon->id }}" >
                    <div class="form-group row">
                        <label class="col-lg-3 col-from-label" for="name"> Coupon Type </label>
                        <div class="col-lg-9">
                            <select name="coupon_type" id="coupon_type" class="form-control aiz-selectpicker" onchange="coupon_form()" required>
                                @if ($coupon->type == "product_base"))
                                    <option value="product_base" selected> For Products </option>
                                @elseif ($coupon->type == "cart_base")
                                    <option value="cart_base"> For Total Orders </option>
                                @endif
                            </select>
                        </div>
                    </div>

                    <div id="coupon_form">

                    </div>
                    <div class="form-group mb-0 text-right">
                        <button type="submit" class="btn btn-primary"> Save </button>
                    </div>
            </form>

            </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>

    </div>
</div>

@endsection

resources/views/backend/coupons/index.blade.php
@extends('backend.layouts.app')

@section('title', 'Coupon List')


@section('js')


@endsection
@section('css')
<style>

</style>
@endsection

@section('content')
<div class="page-content">
    <!-- BEGIN PAGE HEADER-->


    @include('backend.include.beginPageHeader')




    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet box green">

                <div class="portlet-title">

                    <div class="dt-buttons" style="margin-top: 5px;">
                        <a class="dt-button buttons-print btn default" tabindex="0" aria-controls="example"
                            href="{{ route('coupon.create') }}"><span> <i class="fa fa-plus"></i> Create New
                                Coupon</span>

                        </a>
                    </div>

                </div>
                <div class="portlet-body">
                    <table class="table table-striped table-bordered table-hover dt-responsive" width="100%"
                        id="sample_3" cellspacing="0" width="100%"">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Code</th>
                                <th>Type</th>
                                <th>Start Date</th>
                                <th>End Date</th>
                                <th width=" 10%">Options</th>
                            </tr>
                         </thead>
                        <tbody>
                            @foreach($coupons as $key => $coupon)
                            <tr>
                                <td>{{$key+1}}</td>
                                <td>{{$coupon->code}}</td>
                                <td>@if ($coupon->type == 'cart_base')
                                    Cart Base
                                    @elseif ($coupon->type == 'category_base')
                                    Category Base
                                    @endif</td>
                                <td>{{ date('d-m-Y', $coupon->start_date) }}</td>
                                <td>{{ date('d-m-Y', $coupon->end_date) }}</td>
                                <td class="text-right">
                                
                                    <!-- <a href="{{route('coupon.edit', $coupon->id )}}" class="btn btn-icon-pencil blue btn-icon btn-circle btn-sm"
                                         title="Edit">
                                        <i class="ace-icon fa fa-eye bigger-130"></i>
                                    </a> -->
                                    <a href="{{route('coupon_destroy', $coupon->id)}}" class="btn btn-danger btn-icon btn-circle btn-sm confirm-delete" style="border: none;"
                                        data-href="{{route('coupon.destroy', $coupon->id)}}" title="Delete">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>

    </div>
</div>
<!-- END CONTENT BODY -->
@endsection

resources/views/backend/coupons/product_base_coupon.blade.php
<div class="card-header mb-2">
    <h3 class="h6">Add Your Product Base Coupon</h3>
</div>
<div class="form-group row">
    <label class="col-lg-3 col-from-label" for="coupon_code"> Coupon code </label>
    <div class="col-lg-5">
        <input type="text" placeholder=" Coupon code " id="coupon_code" name="coupon_code" class="form-control" required>
    </div>
</div>
<div class="product-choose-list">
    <div class="product-choose">
        <div class="form-group row">
            <label class="col-lg-3 col-from-label" for="name"> Category </label>
            <div class="col-lg-5">
                <select name="product_ids[]"  multiple="multiple" class="form-control product_id" data-live-search="true" data-selected-text-format="count" required>
                    @foreach($all_product as $product)
                        <option value="{{$product->id}}">{{ $product->name }}</option>
                    @endforeach
                </select>
            </div>
        </div>
    </div>
</div>
<br>
<div class="form-group row">
    <label class="col-sm-3 control-label" for="start_date" style="text-align: left;"> Date </label>
    <div class="col-sm-5">
      <input type="text" class="form-control aiz-date-range" name="date_range" placeholder="Select Date">
    </div>
</div>
<div class="form-group row">
   <label class="col-lg-3 col-from-label"> Discount </label>
   <div class="col-lg-3">
      <input type="number" lang="en" min="0" step="0.01" placeholder=" Discount " name="discount" class="form-control" required>
   </div>
   <div class="col-lg-2">
       <select class="form-control aiz-selectpicker" name="discount_type">
           <option value="amount"> Amount </option>
           <option value="percent"> Percent </option>
       </select>
   </div>
</div>


<script type="text/javascript">

    $(document).ready(function(){
        $('.aiz-date-range').daterangepicker();
        AIZ.plugins.bootstrapSelect('refresh');
    });

</script>

resources/views/backend/coupons/product_base_coupon_edit.blade.php
<div class="card-header mb-2">
    <h5 class="mb-0 h6">{{translate('Add Your Product Base Coupon')}}</h5>
</div>
<div class="form-group row">
    <label class="col-lg-3 control-label" for="coupon_code">{{translate('Coupon code')}}</label>
    <div class="col-lg-9">
        <input type="text" placeholder="{{translate('Coupon code')}}" id="coupon_code" name="coupon_code" value="{{ $coupon->code }}" class="form-control" required>
    </div>
</div>
<div class="product-choose-list">
    <div class="product-choose">
        <div class="form-group row">
            <label class="col-lg-3 control-label" for="name">{{translate('Product')}}</label>
            <div class="col-lg-9">
                <select name="product_ids[]" class="form-control product_id aiz-selectpicker" data-live-search="true" data-selected-text-format="count" required multiple>
                    @foreach(filter_products(\App\Product::query())->get() as $key => $product)
                        <option value="{{$product->id}}"
                            @foreach (json_decode($coupon->details) as $key => $details)
                                @if ($details->product_id == $product->id)
                                    selected
                                @endif
                            @endforeach
                            >{{$product->getTranslation('name')}}</option>
                    @endforeach
                </select>
            </div>
        </div>
    </div>
</div>
@php
  $start_date = date('m/d/Y', $coupon->start_date);
  $end_date = date('m/d/Y', $coupon->end_date);
@endphp
<div class="form-group row">
    <label class="col-sm-3 control-label" for="start_date">{{translate('Date')}}</label>
    <div class="col-sm-9">
      <input type="text" class="form-control aiz-date-range" value="{{ $start_date .' - '. $end_date }}" name="date_range" placeholder="Select Date">
    </div>
</div>

<div class="form-group row">
   <label class="col-lg-3 col-from-label">{{translate('Discount')}}</label>
   <div class="col-lg-7">
       <input type="number" lang="en" min="0" step="0.01" placeholder="{{translate('Discount')}}" value="{{ $coupon->discount }}" name="discount" class="form-control" required>

   </div>
   <div class="col-lg-2">
       <select class="form-control aiz-selectpicker" name="discount_type">
           <option value="amount" @if ($coupon->discount_type == 'amount') selected  @endif>{{translate('Amount')}}</option>
           <option value="percent" @if ($coupon->discount_type == 'percent') selected  @endif>{{translate('Percent')}}</option>
       </select>
   </div>
</div>

<script type="text/javascript">

    $(document).ready(function(){
        $('.aiz-date-range').daterangepicker();
        AIZ.plugins.bootstrapSelect('refresh');
    });

</script>